package com.ep.db.dao;

import com.ep.db.domain.HrContractOrg;
import com.ep.db.domain.HrContractOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HrContractOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    long countByExample(HrContractOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    int deleteByExample(HrContractOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    int insert(HrContractOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    int insertSelective(HrContractOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    HrContractOrg selectOneByExample(HrContractOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    HrContractOrg selectOneByExampleSelective(@Param("example") HrContractOrgExample example, @Param("selective") HrContractOrg.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    List<HrContractOrg> selectByExampleSelective(@Param("example") HrContractOrgExample example, @Param("selective") HrContractOrg.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    List<HrContractOrg> selectByExample(HrContractOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    HrContractOrg selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") HrContractOrg.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    HrContractOrg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    HrContractOrg selectByPrimaryKeyWithLogicalDelete(@Param("id") String id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HrContractOrg record, @Param("example") HrContractOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HrContractOrg record, @Param("example") HrContractOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HrContractOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HrContractOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") HrContractOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_contract_org
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(String id);
}