package com.ep.db.dao;

import com.ep.db.domain.HrPersonContract;
import com.ep.db.domain.HrPersonContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HrPersonContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    long countByExample(HrPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    int deleteByExample(HrPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    int insert(HrPersonContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    int insertSelective(HrPersonContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    HrPersonContract selectOneByExample(HrPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    HrPersonContract selectOneByExampleSelective(@Param("example") HrPersonContractExample example, @Param("selective") HrPersonContract.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    List<HrPersonContract> selectByExampleSelective(@Param("example") HrPersonContractExample example, @Param("selective") HrPersonContract.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    List<HrPersonContract> selectByExample(HrPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    HrPersonContract selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") HrPersonContract.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    HrPersonContract selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    HrPersonContract selectByPrimaryKeyWithLogicalDelete(@Param("id") String id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HrPersonContract record, @Param("example") HrPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HrPersonContract record, @Param("example") HrPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HrPersonContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HrPersonContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") HrPersonContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(String id);
}