package com.ep.db.dao;

import com.ep.db.domain.HrSalaryAction;
import com.ep.db.domain.HrSalaryActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HrSalaryActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    long countByExample(HrSalaryActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    int deleteByExample(HrSalaryActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    int insert(HrSalaryAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    int insertSelective(HrSalaryAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    HrSalaryAction selectOneByExample(HrSalaryActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    HrSalaryAction selectOneByExampleSelective(@Param("example") HrSalaryActionExample example, @Param("selective") HrSalaryAction.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    List<HrSalaryAction> selectByExampleSelective(@Param("example") HrSalaryActionExample example, @Param("selective") HrSalaryAction.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    List<HrSalaryAction> selectByExample(HrSalaryActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    HrSalaryAction selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") HrSalaryAction.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    HrSalaryAction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    HrSalaryAction selectByPrimaryKeyWithLogicalDelete(@Param("id") String id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HrSalaryAction record, @Param("example") HrSalaryActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HrSalaryAction record, @Param("example") HrSalaryActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HrSalaryAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HrSalaryAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") HrSalaryActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_salary_action
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(String id);
}