package com.ep.db.domain;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class HrPersonAttendanceRec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hr_person_attendance_rec
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hr_person_attendance_rec
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.employee_id
     *
     * @mbg.generated
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.person_id
     *
     * @mbg.generated
     */
    private String personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.job_number
     *
     * @mbg.generated
     */
    private String jobNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.jb_cnt
     *
     * @mbg.generated
     */
    private BigDecimal jbCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.nj_cnt
     *
     * @mbg.generated
     */
    private BigDecimal njCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.sj_cnt
     *
     * @mbg.generated
     */
    private BigDecimal sjCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.bj_cnt
     *
     * @mbg.generated
     */
    private BigDecimal bjCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.cc_cnt
     *
     * @mbg.generated
     */
    private BigDecimal ccCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.other_cnt
     *
     * @mbg.generated
     */
    private BigDecimal otherCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.rec_time
     *
     * @mbg.generated
     */
    private LocalDate recTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.delete_by
     *
     * @mbg.generated
     */
    private String deleteBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.delete_time
     *
     * @mbg.generated
     */
    private LocalDateTime deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_attendance_rec.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    private HrPerson  hrPerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.id
     *
     * @return the value of hr_person_attendance_rec.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.id
     *
     * @param id the value for hr_person_attendance_rec.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.employee_id
     *
     * @return the value of hr_person_attendance_rec.employee_id
     *
     * @mbg.generated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.employee_id
     *
     * @param employeeId the value for hr_person_attendance_rec.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.person_id
     *
     * @return the value of hr_person_attendance_rec.person_id
     *
     * @mbg.generated
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.person_id
     *
     * @param personId the value for hr_person_attendance_rec.person_id
     *
     * @mbg.generated
     */
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.job_number
     *
     * @return the value of hr_person_attendance_rec.job_number
     *
     * @mbg.generated
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.job_number
     *
     * @param jobNumber the value for hr_person_attendance_rec.job_number
     *
     * @mbg.generated
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.jb_cnt
     *
     * @return the value of hr_person_attendance_rec.jb_cnt
     *
     * @mbg.generated
     */
    public BigDecimal getJbCnt() {
        return jbCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.jb_cnt
     *
     * @param jbCnt the value for hr_person_attendance_rec.jb_cnt
     *
     * @mbg.generated
     */
    public void setJbCnt(BigDecimal jbCnt) {
        this.jbCnt = jbCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.nj_cnt
     *
     * @return the value of hr_person_attendance_rec.nj_cnt
     *
     * @mbg.generated
     */
    public BigDecimal getNjCnt() {
        return njCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.nj_cnt
     *
     * @param njCnt the value for hr_person_attendance_rec.nj_cnt
     *
     * @mbg.generated
     */
    public void setNjCnt(BigDecimal njCnt) {
        this.njCnt = njCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.sj_cnt
     *
     * @return the value of hr_person_attendance_rec.sj_cnt
     *
     * @mbg.generated
     */
    public BigDecimal getSjCnt() {
        return sjCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.sj_cnt
     *
     * @param sjCnt the value for hr_person_attendance_rec.sj_cnt
     *
     * @mbg.generated
     */
    public void setSjCnt(BigDecimal sjCnt) {
        this.sjCnt = sjCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.bj_cnt
     *
     * @return the value of hr_person_attendance_rec.bj_cnt
     *
     * @mbg.generated
     */
    public BigDecimal getBjCnt() {
        return bjCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.bj_cnt
     *
     * @param bjCnt the value for hr_person_attendance_rec.bj_cnt
     *
     * @mbg.generated
     */
    public void setBjCnt(BigDecimal bjCnt) {
        this.bjCnt = bjCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.cc_cnt
     *
     * @return the value of hr_person_attendance_rec.cc_cnt
     *
     * @mbg.generated
     */
    public BigDecimal getCcCnt() {
        return ccCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.cc_cnt
     *
     * @param ccCnt the value for hr_person_attendance_rec.cc_cnt
     *
     * @mbg.generated
     */
    public void setCcCnt(BigDecimal ccCnt) {
        this.ccCnt = ccCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.other_cnt
     *
     * @return the value of hr_person_attendance_rec.other_cnt
     *
     * @mbg.generated
     */
    public BigDecimal getOtherCnt() {
        return otherCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.other_cnt
     *
     * @param otherCnt the value for hr_person_attendance_rec.other_cnt
     *
     * @mbg.generated
     */
    public void setOtherCnt(BigDecimal otherCnt) {
        this.otherCnt = otherCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.rec_time
     *
     * @return the value of hr_person_attendance_rec.rec_time
     *
     * @mbg.generated
     */
    public LocalDate getRecTime() {
        return recTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.rec_time
     *
     * @param recTime the value for hr_person_attendance_rec.rec_time
     *
     * @mbg.generated
     */
    public void setRecTime(LocalDate recTime) {
        this.recTime = recTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.notes
     *
     * @return the value of hr_person_attendance_rec.notes
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.notes
     *
     * @param notes the value for hr_person_attendance_rec.notes
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.create_by
     *
     * @return the value of hr_person_attendance_rec.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.create_by
     *
     * @param createBy the value for hr_person_attendance_rec.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.create_time
     *
     * @return the value of hr_person_attendance_rec.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.create_time
     *
     * @param createTime the value for hr_person_attendance_rec.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.update_by
     *
     * @return the value of hr_person_attendance_rec.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.update_by
     *
     * @param updateBy the value for hr_person_attendance_rec.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.update_time
     *
     * @return the value of hr_person_attendance_rec.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.update_time
     *
     * @param updateTime the value for hr_person_attendance_rec.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_attendance_rec
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.deleted
     *
     * @return the value of hr_person_attendance_rec.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.deleted
     *
     * @param deleted the value for hr_person_attendance_rec.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.delete_by
     *
     * @return the value of hr_person_attendance_rec.delete_by
     *
     * @mbg.generated
     */
    public String getDeleteBy() {
        return deleteBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.delete_by
     *
     * @param deleteBy the value for hr_person_attendance_rec.delete_by
     *
     * @mbg.generated
     */
    public void setDeleteBy(String deleteBy) {
        this.deleteBy = deleteBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.delete_time
     *
     * @return the value of hr_person_attendance_rec.delete_time
     *
     * @mbg.generated
     */
    public LocalDateTime getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.delete_time
     *
     * @param deleteTime the value for hr_person_attendance_rec.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(LocalDateTime deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.version
     *
     * @return the value of hr_person_attendance_rec.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.version
     *
     * @param version the value for hr_person_attendance_rec.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_attendance_rec.tenant_id
     *
     * @return the value of hr_person_attendance_rec.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_attendance_rec.tenant_id
     *
     * @param tenantId the value for hr_person_attendance_rec.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    public HrPerson getHrPerson() {
        return hrPerson;
    }

    public void setHrPerson(HrPerson hrPerson) {
        this.hrPerson = hrPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_attendance_rec
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", employeeId=").append(employeeId);
        sb.append(", personId=").append(personId);
        sb.append(", jobNumber=").append(jobNumber);
        sb.append(", jbCnt=").append(jbCnt);
        sb.append(", njCnt=").append(njCnt);
        sb.append(", sjCnt=").append(sjCnt);
        sb.append(", bjCnt=").append(bjCnt);
        sb.append(", ccCnt=").append(ccCnt);
        sb.append(", otherCnt=").append(otherCnt);
        sb.append(", recTime=").append(recTime);
        sb.append(", notes=").append(notes);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", deleteBy=").append(deleteBy);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", version=").append(version);
        sb.append(", tenantId=").append(tenantId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_attendance_rec
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HrPersonAttendanceRec other = (HrPersonAttendanceRec) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEmployeeId() == null ? other.getEmployeeId() == null : this.getEmployeeId().equals(other.getEmployeeId()))
            && (this.getPersonId() == null ? other.getPersonId() == null : this.getPersonId().equals(other.getPersonId()))
            && (this.getJobNumber() == null ? other.getJobNumber() == null : this.getJobNumber().equals(other.getJobNumber()))
            && (this.getJbCnt() == null ? other.getJbCnt() == null : this.getJbCnt().equals(other.getJbCnt()))
            && (this.getNjCnt() == null ? other.getNjCnt() == null : this.getNjCnt().equals(other.getNjCnt()))
            && (this.getSjCnt() == null ? other.getSjCnt() == null : this.getSjCnt().equals(other.getSjCnt()))
            && (this.getBjCnt() == null ? other.getBjCnt() == null : this.getBjCnt().equals(other.getBjCnt()))
            && (this.getCcCnt() == null ? other.getCcCnt() == null : this.getCcCnt().equals(other.getCcCnt()))
            && (this.getOtherCnt() == null ? other.getOtherCnt() == null : this.getOtherCnt().equals(other.getOtherCnt()))
            && (this.getRecTime() == null ? other.getRecTime() == null : this.getRecTime().equals(other.getRecTime()))
            && (this.getNotes() == null ? other.getNotes() == null : this.getNotes().equals(other.getNotes()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getDeleteBy() == null ? other.getDeleteBy() == null : this.getDeleteBy().equals(other.getDeleteBy()))
            && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_attendance_rec
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEmployeeId() == null) ? 0 : getEmployeeId().hashCode());
        result = prime * result + ((getPersonId() == null) ? 0 : getPersonId().hashCode());
        result = prime * result + ((getJobNumber() == null) ? 0 : getJobNumber().hashCode());
        result = prime * result + ((getJbCnt() == null) ? 0 : getJbCnt().hashCode());
        result = prime * result + ((getNjCnt() == null) ? 0 : getNjCnt().hashCode());
        result = prime * result + ((getSjCnt() == null) ? 0 : getSjCnt().hashCode());
        result = prime * result + ((getBjCnt() == null) ? 0 : getBjCnt().hashCode());
        result = prime * result + ((getCcCnt() == null) ? 0 : getCcCnt().hashCode());
        result = prime * result + ((getOtherCnt() == null) ? 0 : getOtherCnt().hashCode());
        result = prime * result + ((getRecTime() == null) ? 0 : getRecTime().hashCode());
        result = prime * result + ((getNotes() == null) ? 0 : getNotes().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getDeleteBy() == null) ? 0 : getDeleteBy().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hr_person_attendance_rec
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hr_person_attendance_rec
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "VARCHAR", false),
        employeeId("employee_id", "employeeId", "VARCHAR", false),
        personId("person_id", "personId", "VARCHAR", false),
        jobNumber("job_number", "jobNumber", "VARCHAR", false),
        jbCnt("jb_cnt", "jbCnt", "DECIMAL", false),
        njCnt("nj_cnt", "njCnt", "DECIMAL", false),
        sjCnt("sj_cnt", "sjCnt", "DECIMAL", false),
        bjCnt("bj_cnt", "bjCnt", "DECIMAL", false),
        ccCnt("cc_cnt", "ccCnt", "DECIMAL", false),
        otherCnt("other_cnt", "otherCnt", "DECIMAL", false),
        recTime("rec_time", "recTime", "DATE", false),
        notes("notes", "notes", "VARCHAR", false),
        createBy("create_by", "createBy", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateBy("update_by", "updateBy", "VARCHAR", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        deleteBy("delete_by", "deleteBy", "VARCHAR", false),
        deleteTime("delete_time", "deleteTime", "TIMESTAMP", false),
        version("version", "version", "INTEGER", false),
        tenantId("tenant_id", "tenantId", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_attendance_rec
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}