package com.ep.db.domain;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class HrPersonContract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.person_id
     *
     * @mbg.generated
     */
    private String personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.business_code
     *
     * @mbg.generated
     */
    private String businessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.contract_duration
     *
     * @mbg.generated
     */
    private BigDecimal contractDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.contract_year
     *
     * @mbg.generated
     */
    private String contractYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.transfer_to_regular
     *
     * @mbg.generated
     */
    private String transferToRegular;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.contract_party_id
     *
     * @mbg.generated
     */
    private String contractPartyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.probation_salary
     *
     * @mbg.generated
     */
    private BigDecimal probationSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.probation_start_date
     *
     * @mbg.generated
     */
    private LocalDate probationStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.probation_finish_date
     *
     * @mbg.generated
     */
    private LocalDate probationFinishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.contract_start_date
     *
     * @mbg.generated
     */
    private LocalDate contractStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.contract_finish_date
     *
     * @mbg.generated
     */
    private LocalDate contractFinishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.salary
     *
     * @mbg.generated
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.file_id
     *
     * @mbg.generated
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.arch
     *
     * @mbg.generated
     */
    private String arch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.delete_by
     *
     * @mbg.generated
     */
    private String deleteBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.delete_time
     *
     * @mbg.generated
     */
    private LocalDateTime deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hr_person_contract.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    private  HrPerson  hrPerson;

    private HrContractOrg  hrContractOrg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.id
     *
     * @return the value of hr_person_contract.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.id
     *
     * @param id the value for hr_person_contract.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.person_id
     *
     * @return the value of hr_person_contract.person_id
     *
     * @mbg.generated
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.person_id
     *
     * @param personId the value for hr_person_contract.person_id
     *
     * @mbg.generated
     */
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.business_code
     *
     * @return the value of hr_person_contract.business_code
     *
     * @mbg.generated
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.business_code
     *
     * @param businessCode the value for hr_person_contract.business_code
     *
     * @mbg.generated
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.type
     *
     * @return the value of hr_person_contract.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.type
     *
     * @param type the value for hr_person_contract.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.status
     *
     * @return the value of hr_person_contract.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.status
     *
     * @param status the value for hr_person_contract.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.contract_duration
     *
     * @return the value of hr_person_contract.contract_duration
     *
     * @mbg.generated
     */
    public BigDecimal getContractDuration() {
        return contractDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.contract_duration
     *
     * @param contractDuration the value for hr_person_contract.contract_duration
     *
     * @mbg.generated
     */
    public void setContractDuration(BigDecimal contractDuration) {
        this.contractDuration = contractDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.contract_year
     *
     * @return the value of hr_person_contract.contract_year
     *
     * @mbg.generated
     */
    public String getContractYear() {
        return contractYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.contract_year
     *
     * @param contractYear the value for hr_person_contract.contract_year
     *
     * @mbg.generated
     */
    public void setContractYear(String contractYear) {
        this.contractYear = contractYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.transfer_to_regular
     *
     * @return the value of hr_person_contract.transfer_to_regular
     *
     * @mbg.generated
     */
    public String getTransferToRegular() {
        return transferToRegular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.transfer_to_regular
     *
     * @param transferToRegular the value for hr_person_contract.transfer_to_regular
     *
     * @mbg.generated
     */
    public void setTransferToRegular(String transferToRegular) {
        this.transferToRegular = transferToRegular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.contract_party_id
     *
     * @return the value of hr_person_contract.contract_party_id
     *
     * @mbg.generated
     */
    public String getContractPartyId() {
        return contractPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.contract_party_id
     *
     * @param contractPartyId the value for hr_person_contract.contract_party_id
     *
     * @mbg.generated
     */
    public void setContractPartyId(String contractPartyId) {
        this.contractPartyId = contractPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.probation_salary
     *
     * @return the value of hr_person_contract.probation_salary
     *
     * @mbg.generated
     */
    public BigDecimal getProbationSalary() {
        return probationSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.probation_salary
     *
     * @param probationSalary the value for hr_person_contract.probation_salary
     *
     * @mbg.generated
     */
    public void setProbationSalary(BigDecimal probationSalary) {
        this.probationSalary = probationSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.probation_start_date
     *
     * @return the value of hr_person_contract.probation_start_date
     *
     * @mbg.generated
     */
    public LocalDate getProbationStartDate() {
        return probationStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.probation_start_date
     *
     * @param probationStartDate the value for hr_person_contract.probation_start_date
     *
     * @mbg.generated
     */
    public void setProbationStartDate(LocalDate probationStartDate) {
        this.probationStartDate = probationStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.probation_finish_date
     *
     * @return the value of hr_person_contract.probation_finish_date
     *
     * @mbg.generated
     */
    public LocalDate getProbationFinishDate() {
        return probationFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.probation_finish_date
     *
     * @param probationFinishDate the value for hr_person_contract.probation_finish_date
     *
     * @mbg.generated
     */
    public void setProbationFinishDate(LocalDate probationFinishDate) {
        this.probationFinishDate = probationFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.contract_start_date
     *
     * @return the value of hr_person_contract.contract_start_date
     *
     * @mbg.generated
     */
    public LocalDate getContractStartDate() {
        return contractStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.contract_start_date
     *
     * @param contractStartDate the value for hr_person_contract.contract_start_date
     *
     * @mbg.generated
     */
    public void setContractStartDate(LocalDate contractStartDate) {
        this.contractStartDate = contractStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.contract_finish_date
     *
     * @return the value of hr_person_contract.contract_finish_date
     *
     * @mbg.generated
     */
    public LocalDate getContractFinishDate() {
        return contractFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.contract_finish_date
     *
     * @param contractFinishDate the value for hr_person_contract.contract_finish_date
     *
     * @mbg.generated
     */
    public void setContractFinishDate(LocalDate contractFinishDate) {
        this.contractFinishDate = contractFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.salary
     *
     * @return the value of hr_person_contract.salary
     *
     * @mbg.generated
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.salary
     *
     * @param salary the value for hr_person_contract.salary
     *
     * @mbg.generated
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.content
     *
     * @return the value of hr_person_contract.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.content
     *
     * @param content the value for hr_person_contract.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.notes
     *
     * @return the value of hr_person_contract.notes
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.notes
     *
     * @param notes the value for hr_person_contract.notes
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.file_id
     *
     * @return the value of hr_person_contract.file_id
     *
     * @mbg.generated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.file_id
     *
     * @param fileId the value for hr_person_contract.file_id
     *
     * @mbg.generated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.arch
     *
     * @return the value of hr_person_contract.arch
     *
     * @mbg.generated
     */
    public String getArch() {
        return arch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.arch
     *
     * @param arch the value for hr_person_contract.arch
     *
     * @mbg.generated
     */
    public void setArch(String arch) {
        this.arch = arch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.create_by
     *
     * @return the value of hr_person_contract.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.create_by
     *
     * @param createBy the value for hr_person_contract.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.create_time
     *
     * @return the value of hr_person_contract.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.create_time
     *
     * @param createTime the value for hr_person_contract.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.update_by
     *
     * @return the value of hr_person_contract.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.update_by
     *
     * @param updateBy the value for hr_person_contract.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.update_time
     *
     * @return the value of hr_person_contract.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.update_time
     *
     * @param updateTime the value for hr_person_contract.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.deleted
     *
     * @return the value of hr_person_contract.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.deleted
     *
     * @param deleted the value for hr_person_contract.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.delete_by
     *
     * @return the value of hr_person_contract.delete_by
     *
     * @mbg.generated
     */
    public String getDeleteBy() {
        return deleteBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.delete_by
     *
     * @param deleteBy the value for hr_person_contract.delete_by
     *
     * @mbg.generated
     */
    public void setDeleteBy(String deleteBy) {
        this.deleteBy = deleteBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.delete_time
     *
     * @return the value of hr_person_contract.delete_time
     *
     * @mbg.generated
     */
    public LocalDateTime getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.delete_time
     *
     * @param deleteTime the value for hr_person_contract.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(LocalDateTime deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.version
     *
     * @return the value of hr_person_contract.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.version
     *
     * @param version the value for hr_person_contract.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hr_person_contract.tenant_id
     *
     * @return the value of hr_person_contract.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hr_person_contract.tenant_id
     *
     * @param tenantId the value for hr_person_contract.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    public HrPerson getHrPerson() {
        return hrPerson;
    }

    public void setHrPerson(HrPerson hrPerson) {
        this.hrPerson = hrPerson;
    }

    public HrContractOrg getHrContractOrg() {
        return hrContractOrg;
    }

    public void setHrContractOrg(HrContractOrg hrContractOrg) {
        this.hrContractOrg = hrContractOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", personId=").append(personId);
        sb.append(", businessCode=").append(businessCode);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", contractDuration=").append(contractDuration);
        sb.append(", contractYear=").append(contractYear);
        sb.append(", transferToRegular=").append(transferToRegular);
        sb.append(", contractPartyId=").append(contractPartyId);
        sb.append(", probationSalary=").append(probationSalary);
        sb.append(", probationStartDate=").append(probationStartDate);
        sb.append(", probationFinishDate=").append(probationFinishDate);
        sb.append(", contractStartDate=").append(contractStartDate);
        sb.append(", contractFinishDate=").append(contractFinishDate);
        sb.append(", salary=").append(salary);
        sb.append(", content=").append(content);
        sb.append(", notes=").append(notes);
        sb.append(", fileId=").append(fileId);
        sb.append(", arch=").append(arch);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", deleteBy=").append(deleteBy);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", version=").append(version);
        sb.append(", tenantId=").append(tenantId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HrPersonContract other = (HrPersonContract) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPersonId() == null ? other.getPersonId() == null : this.getPersonId().equals(other.getPersonId()))
            && (this.getBusinessCode() == null ? other.getBusinessCode() == null : this.getBusinessCode().equals(other.getBusinessCode()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getContractDuration() == null ? other.getContractDuration() == null : this.getContractDuration().equals(other.getContractDuration()))
            && (this.getContractYear() == null ? other.getContractYear() == null : this.getContractYear().equals(other.getContractYear()))
            && (this.getTransferToRegular() == null ? other.getTransferToRegular() == null : this.getTransferToRegular().equals(other.getTransferToRegular()))
            && (this.getContractPartyId() == null ? other.getContractPartyId() == null : this.getContractPartyId().equals(other.getContractPartyId()))
            && (this.getProbationSalary() == null ? other.getProbationSalary() == null : this.getProbationSalary().equals(other.getProbationSalary()))
            && (this.getProbationStartDate() == null ? other.getProbationStartDate() == null : this.getProbationStartDate().equals(other.getProbationStartDate()))
            && (this.getProbationFinishDate() == null ? other.getProbationFinishDate() == null : this.getProbationFinishDate().equals(other.getProbationFinishDate()))
            && (this.getContractStartDate() == null ? other.getContractStartDate() == null : this.getContractStartDate().equals(other.getContractStartDate()))
            && (this.getContractFinishDate() == null ? other.getContractFinishDate() == null : this.getContractFinishDate().equals(other.getContractFinishDate()))
            && (this.getSalary() == null ? other.getSalary() == null : this.getSalary().equals(other.getSalary()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getNotes() == null ? other.getNotes() == null : this.getNotes().equals(other.getNotes()))
            && (this.getFileId() == null ? other.getFileId() == null : this.getFileId().equals(other.getFileId()))
            && (this.getArch() == null ? other.getArch() == null : this.getArch().equals(other.getArch()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getDeleteBy() == null ? other.getDeleteBy() == null : this.getDeleteBy().equals(other.getDeleteBy()))
            && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPersonId() == null) ? 0 : getPersonId().hashCode());
        result = prime * result + ((getBusinessCode() == null) ? 0 : getBusinessCode().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getContractDuration() == null) ? 0 : getContractDuration().hashCode());
        result = prime * result + ((getContractYear() == null) ? 0 : getContractYear().hashCode());
        result = prime * result + ((getTransferToRegular() == null) ? 0 : getTransferToRegular().hashCode());
        result = prime * result + ((getContractPartyId() == null) ? 0 : getContractPartyId().hashCode());
        result = prime * result + ((getProbationSalary() == null) ? 0 : getProbationSalary().hashCode());
        result = prime * result + ((getProbationStartDate() == null) ? 0 : getProbationStartDate().hashCode());
        result = prime * result + ((getProbationFinishDate() == null) ? 0 : getProbationFinishDate().hashCode());
        result = prime * result + ((getContractStartDate() == null) ? 0 : getContractStartDate().hashCode());
        result = prime * result + ((getContractFinishDate() == null) ? 0 : getContractFinishDate().hashCode());
        result = prime * result + ((getSalary() == null) ? 0 : getSalary().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getNotes() == null) ? 0 : getNotes().hashCode());
        result = prime * result + ((getFileId() == null) ? 0 : getFileId().hashCode());
        result = prime * result + ((getArch() == null) ? 0 : getArch().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getDeleteBy() == null) ? 0 : getDeleteBy().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table hr_person_contract
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "VARCHAR", false),
        personId("person_id", "personId", "VARCHAR", false),
        businessCode("business_code", "businessCode", "VARCHAR", false),
        type("type", "type", "VARCHAR", true),
        status("status", "status", "VARCHAR", true),
        contractDuration("contract_duration", "contractDuration", "DECIMAL", false),
        contractYear("contract_year", "contractYear", "VARCHAR", false),
        transferToRegular("transfer_to_regular", "transferToRegular", "VARCHAR", false),
        contractPartyId("contract_party_id", "contractPartyId", "VARCHAR", false),
        probationSalary("probation_salary", "probationSalary", "DECIMAL", false),
        probationStartDate("probation_start_date", "probationStartDate", "DATE", false),
        probationFinishDate("probation_finish_date", "probationFinishDate", "DATE", false),
        contractStartDate("contract_start_date", "contractStartDate", "DATE", false),
        contractFinishDate("contract_finish_date", "contractFinishDate", "DATE", false),
        salary("salary", "salary", "DECIMAL", false),
        content("content", "content", "VARCHAR", false),
        notes("notes", "notes", "VARCHAR", false),
        fileId("file_id", "fileId", "VARCHAR", false),
        arch("arch", "arch", "VARCHAR", false),
        createBy("create_by", "createBy", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateBy("update_by", "updateBy", "VARCHAR", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        deleteBy("delete_by", "deleteBy", "VARCHAR", false),
        deleteTime("delete_time", "deleteTime", "TIMESTAMP", false),
        version("version", "version", "INTEGER", false),
        tenantId("tenant_id", "tenantId", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table hr_person_contract
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}